"""empty message

Revision ID: 125c48c8e127
Revises: df2052c4588a
Create Date: 2020-05-26 16:01:41.344310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '125c48c8e127'
down_revision = 'df2052c4588a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_index('account', table_name='admins')
    op.drop_table('admins')
    op.drop_table('user_course')
    op.drop_table('scores')
    op.drop_table('user_search_histories')
    op.drop_table('modules')
    op.create_foreign_key(None, 'courses', 'users', ['user_id'], ['id'])
    op.drop_column('courses', 'content')
    op.drop_column('courses', 'view_num')
    op.drop_column('courses', 'created_at')
    op.drop_column('courses', 'module_id')
    op.drop_column('courses', 'type')
    op.drop_column('courses', 'score')
    op.drop_column('courses', 'cover')
    op.drop_column('courses', 'videos')
    op.drop_column('courses', 'collect_num')
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'name')
    op.drop_column('users', 'sex')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('sex', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('courses', sa.Column('collect_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('videos', mysql.TEXT(), nullable=True))
    op.add_column('courses', sa.Column('cover', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('courses', sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('module_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('courses', sa.Column('view_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('content', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_table('modules',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('user_search_histories',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('scores',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('user_course',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('admins',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('account', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('institution', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('post_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_index('account', 'admins', ['account'], unique=True)
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('from_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('to_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
