"""empty message

Revision ID: 44315dec3b07
Revises: 
Create Date: 2020-05-26 08:24:00.516382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44315dec3b07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('advatar', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
