"""empty message

Revision ID: a275092fac74
Revises: 44315dec3b07
Create Date: 2020-05-26 08:38:16.978312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a275092fac74'
down_revision = '44315dec3b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('post_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('account', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('describe', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('sex', sa.String(length=10), nullable=True))
    op.drop_column('users', 'advatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('advatar', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'sex')
    op.drop_column('users', 'password')
    op.drop_column('users', 'describe')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'age')
    op.drop_column('users', 'account')
    op.drop_table('admins')
    # ### end Alembic commands ###
