"""empty message

Revision ID: bd1438342b20
Revises: 2d4f64e5e122
Create Date: 2020-05-26 13:18:00.952371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd1438342b20'
down_revision = '2d4f64e5e122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_course',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.alter_column('admins', 'account',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('admins', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'admins', ['account'])
    op.alter_column('courses', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'courses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'courses', 'modules', ['module_id'], ['id'])
    op.alter_column('users', 'account',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['account'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'account',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.alter_column('courses', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'admins', type_='unique')
    op.alter_column('admins', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('admins', 'account',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_table('user_course')
    op.drop_table('scores')
    op.drop_table('comments')
    # ### end Alembic commands ###
