"""empty message

Revision ID: c99fa7b4b5ab
Revises: a9b18d7b095c
Create Date: 2020-05-26 17:33:39.701112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99fa7b4b5ab'
down_revision = 'a9b18d7b095c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'courses', 'modules', ['module_id'], ['id'])
    op.create_foreign_key(None, 'courses', 'admins', ['user_id'], ['id'])
    op.create_foreign_key(None, 'scores', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'scores', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_course', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'user_course', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_search_histories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_search_histories', type_='foreignkey')
    op.drop_constraint(None, 'user_course', type_='foreignkey')
    op.drop_constraint(None, 'user_course', type_='foreignkey')
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
